# Auto generated by ct-mksetup
# Do not edit this file, edit ./project.py instead

from setuptools import setup
setup(
    **{   'author': 'Tim Diels',
    'author_email': 'timdiels.m@gmail.com',
    'classifiers': [   'Natural Language :: English',
                       'Intended Audience :: Developers',
                       'Development Status :: 2 - Pre-Alpha',
                       'Topic :: Software Development',
                       'Topic :: Software Development :: Libraries',
                       'Operating System :: POSIX',
                       'Operating System :: POSIX :: AIX',
                       'Operating System :: POSIX :: BSD',
                       'Operating System :: POSIX :: BSD :: BSD/OS',
                       'Operating System :: POSIX :: BSD :: FreeBSD',
                       'Operating System :: POSIX :: BSD :: NetBSD',
                       'Operating System :: POSIX :: BSD :: OpenBSD',
                       'Operating System :: POSIX :: GNU Hurd',
                       'Operating System :: POSIX :: HP-UX',
                       'Operating System :: POSIX :: IRIX',
                       'Operating System :: POSIX :: Linux',
                       'Operating System :: POSIX :: Other',
                       'Operating System :: POSIX :: SCO',
                       'Operating System :: POSIX :: SunOS/Solaris',
                       'Operating System :: Unix',
                       'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
                       'Programming Language :: Python',
                       'Programming Language :: Python :: 3',
                       'Programming Language :: Python :: 3 :: Only',
                       'Programming Language :: Python :: 3.2',
                       'Programming Language :: Python :: 3.3',
                       'Programming Language :: Python :: 3.4',
                       'Programming Language :: Python :: 3.5',
                       'Programming Language :: Python :: Implementation',
                       'Programming Language :: Python :: Implementation :: CPython',
                       'Programming Language :: Python :: Implementation :: Stackless'],
    'description': 'Python 3 utility library',
    'install_requires': ['pytest'],
    'keywords': 'development util library',
    'license': 'LGPL3',
    'long_description': 'Python 3 utility library. Looks like a turtle, tastes like chicken.\n'
                        '\n'
                        'Chicken Turtle Util (CTU) provides various an API of Python utility\n'
                        'functions.\n'
                        '\n'
                        'Chicken Turtle Util is pre-alpha. None of the interface is stable,\n'
                        'meaning it may change in the future.\n'
                        '\n'
                        'Chicken Turtle Util has some optional dependencies. E.g. to use\n'
                        "``chicken_turtle.pyqt``, you will need to add PyQt to your project's\n"
                        "dependencies. For now, you'll have to let the ``ImportError``\\ s guide\n"
                        'you to the right dependencies to add to setup.py assuming your tests\n'
                        'have full coverage.\n'
                        '\n'
                        'Project decisions\n'
                        '-----------------\n'
                        '\n'
                        'API design\n'
                        '~~~~~~~~~~\n'
                        '\n'
                        "If it's a path, expect a ``pathlib.Path``, not a ``str``.\n",
    'name': 'chicken-turtle-util',
    'package_data': {},
    'packages': ['chicken_turtle_util', 'chicken_turtle_util.test'],
    'url': 'https://github.com/timdiels/chicken_turtle_util',
    'version': '0.0.0'}
)
